[workspace]
members = [
]
exclude = [
    "deps/wchar",
    "deps/wchar",
]

[package]
name = "libexpat-rs"
authors = ["C2Rust"]
version = "0.0.0"
publish = false
edition = "2018"
autobins = false

[lib]
name = "libexpat_rs"
path = "lib.rs"
crate-type = ["staticlib", "rlib"]


[[bin]]
path = "src/examples/outline.rs"
name = "outline"

[[bin]]
path = "src/examples/elements.rs"
name = "elements"

[[bin]]
path = "src/xmlwf/xmlwf.rs"
name = "xmlwf"

[[bin]]
path = "src/tests/runtests.rs"
name = "runtests"

[dependencies]
libc = "0.2"
wchar = { path = "deps/wchar", optional = true }

[features]
default = []
unicode = []
unicode_wchar_t = ["wchar"]
