[workspace]
members = [
]
exclude = [
    "deps/wchar",
    "deps/wchar",
]

[package]
name = "c2rust_out"
authors = ["C2Rust"]
version = "0.0.0"
publish = false
edition = "2018"
autobins = false

[lib]
name = "c2rust_out"
path = "lib.rs"
crate-type = ["staticlib", "rlib"]


[[bin]]
path = "src/examples/outline.rs"
name = "outline"
required-features = ["examples"]

[[bin]]
path = "src/examples/elements.rs"
name = "elements"
required-features = ["examples"]

[[bin]]
path = "src/xmlwf/xmlwf.rs"
name = "xmlwf"
required-features = ["tools"]

[[bin]]
path = "src/tests/runtests.rs"
name = "runtests"
required-features = ["tests"]

[dependencies]
libc = "0.2"
wchar = { path = "deps/wchar" }

[features]
default = ["tests"]
unicode = []
unicode_wchar_t = []
tests = []
tools = []
examples = []
