[package]
name = "libexpat-rs"
authors = ["C2Rust"]
version = "0.0.0"
publish = false
edition = "2018"
autobins = false

[lib]
name = "libexpat_rs"
crate-type = ["staticlib", "rlib"]

[[bin]]
path = "src/examples/outline.rs"
name = "outline"
required-features = ["examples"]

[[bin]]
path = "src/examples/elements.rs"
name = "elements"
required-features = ["examples"]

[[bin]]
path = "src/xmlwf/xmlwf.rs"
name = "xmlwf"
required-features = ["tools"]

[[bin]]
path = "src/tests/runtests.rs"
name = "runtests"
required-features = ["tests"]

[dependencies]
libc = "0.2"
wchar = { path = "deps/wchar", optional = true }

[features]
default = ["tests", "tools"]
unicode = []
tests = []
tools = []
examples = []
unicode_wchar_t = ["wchar"]
getrandom_syscall = []
mozilla = ["unicode"]
